MainEffects      ::= ((TriggeredAbility | ContinuousAbility) (WS WS)?)*

TriggeredAbility ::= TriggerEvent WS* DASH TriggerAction | TriggerEvent TriggerAction

ContinuousAbility ::= (WS*)? ("[]"*)? (TriggerActionCondition COLON)? WS* ContinousEffects

EchoAbility      ::= "{d}" COLON TriggerAction

TriggerEvent     ::= TriggerFromHand | TriggerFromReserve | TriggerEnterPlay | TriggerNoon | TriggerDusk | TriggerMoveToReserveFromExpedition | TriggerMoveToReserveFromHand | TriggerLeaveExpedition | TriggerExpeditionFailedToMove | TriggerPlaySpell | TriggerPlayPermanent | TriggerPlayCharacterWithStats0 | TriggerCharacterJoinsExpeditions | TriggerOppDrawOrResupply | TriggerSacrificeSelf | TriggerCardLeavesReserve | TriggerCreateToken | TriggerRollDice | TriggerCharacterGainsBoost | TriggerSelfGainBoost | TriggerExpeditionMoveDueToV

TriggerFromHand     ::= "{h}" WS*
TriggerEnterPlay    ::= "{j}" WS*
TriggerFromReserve  ::= "{r}" WS*

TriggerNoon         ::= "at noon"
TriggerDusk         ::= "at dusk"

TriggerLeaveExpedition              ::= "when i leave the expedition zone"
TriggerMoveToReserveFromExpedition  ::= "when i go to reserve from the expedition zone"
TriggerMoveToReserveFromHand        ::= "when i go to reserve from your hand"
TriggerExpeditionFailedToMove       ::= "when my expedition fails to move forward during dusk"
TriggerPlaySpell                    ::= "when you play a spell"
TriggerPlayPermanent                ::= "when you play a permanent" (TriggerPlayPermanentRestriction)?
TriggerPlayCharacterWithStats0      ::= "when you play another character with a base statistic of 0" 
TriggerCharacterJoinsExpeditions    ::= "when another" WS* CharacterRestrictionNontoken? WS* (CharacterType | "character") WS* "joins your expeditions"
TriggerOppDrawOrResupply            ::= "when an opponent draws one or more cards or does [resupply]"
TriggerSacrificeSelf                ::= "when i'm sacrificed"
TriggerCardLeavesReserve            ::= "when a card leaves your reserve during the afternoon"
TriggerCreateToken                  ::= "when you create a token"
TriggerRollDice                     ::= "when you roll one or more dice"
TriggerCharacterGainsBoost          ::= "when a character you control gains 1 or more boosts"
TriggerSelfGainBoost                ::= "when i gain 1 or more boosts"
TriggerExpeditionMoveDueToV         ::= "when one of your expeditions moves forward due to {v}"

TriggerActionCondition  ::= ("if" | ConditionInverse) WS* (ConditionControlLandmark | ConditionControlCharacters | ConditionControlCharacterTypes | ConditionControlToken | ConditionSelfHasBoosts | ConditionHaveManaOrbs | ConditionControlStats0)

CharacterRestrictionNontoken    ::= "non-token"
TriggerPlayPermanentRestriction ::= WS* (RestrictionHandCostLessThan | RestrictionHandCostMoreThan) WS*

ConditionSelfHasBoosts ::= "i have" Amount "or more boosts"
ConditionControlLandmark  ::= "you control" TextQuantity "landmark" "s"?
ConditionControlCharacters ::= "you control" TextQuantity ConditionControlBoosted? "character" "s"?
ConditionControlCharacterTypes ::= "you control" TextQuantity WS* CharacterType WS* ConditionOtherThanMe?
ConditionControlToken ::= "you control" TextQuantity "token" "s"?
ConditionHaveManaOrbs  ::= "you have" TextQuantity "mana orbs"
ConditionControlStats0 ::= "you have" TextQuantity "base statistics of 0 among characters you control"

ConditionInverse       ::= "unless"

ConditionControlBoosted ::= WS* "[[boosted]]" WS*

ConditionOtherThanMe  ::= "other than me"

TriggerActionCost   ::= ActionCostHandToReserve | ActionCostHandToReserveRestricted | ActionCostDiscardFromReserve | ActionCostDiscardManaOrb | ActionCostPayMana | ActionCostSacrifice

ActionCostHandToReserve ::= "you may put a card from your hand in reserve. if you do"
ActionCostHandToReserveRestricted ::= "you may put a card from your hand in reserve. if it's a" WS* CardType
ActionCostDiscardFromReserve ::= "you may discard a card from your reserve. if you do"
ActionCostPayMana  ::= "you may pay" ManaValue ". if you do"

ActionCostDiscardManaOrb    ::= "you may discard one of your mana orbs. if you do"

ActionCostSacrifice      ::= ActionCostSacrificeAny | ActionCostSacrificeSelf
ActionCostSacrificeAny   ::= "you may sacrifice" TextQuantity CardTypeDiscardable ". if you do"
ActionCostSacrificeSelf  ::= "you may sacrifice me. if you do"

AfterRestModifier      ::= "after rest:"

TriggerAction     ::= ((TriggerActionCondition | TriggerActionCost) COLON)? AfterRestModifier? WS* ("[]"*)? WS* ActionContents "."


ContinousEffects  ::= (ContinousEffectContentNotEndingWithPeriod) | (ContinousEffectContent ".")

ContinousEffectContent ::= EffectExpeditionCantMoveForward | EffectOtherCharactersAre | EffectTokensYouControlAre | EffectIAm | EffectKraken | EffectMinimumManaToPlay | EffectReducedCost | EffectToughXRegions | EffectPreventJHR | EffectTax | EffectExtraRoll | EffectResupplyLookAt2

ContinousEffectContentNotEndingWithPeriod ::= (EffectCharactersHaveR | EffectRollAddOne)

EffectIAm           ::= "i am" WS* AbilityWord
EffectOtherCharactersAre   ::= "characters you control other than me are" WS* AbilityWord
EffectTokensYouControlAre ::= "tokens you control are" WS* AbilityWord
EffectExpeditionCantMoveForward ::= "your other expedition (the one i'm not in) and the expedition facing it can't move forward"
EffectCharactersHaveR ::= 'your characters have: "{r} i gain' Amount 'boost."'
EffectKraken        ::= "all regions are {o} and lose their other types"
EffectMinimumManaToPlay ::= "i can't be played if you have less than" TextQuantity "mana orbs"
EffectReducedCost   ::= "i cost" ManaValue "less"
EffectToughXRegions ::= "i am [tough x], where x is the number of regions between your hero and companion"
EffectPreventJHR    ::= "the {j}, {h} and {r} abilities of characters facing me can't activate"
EffectTax           ::= (CardTypeCharacter | "cards") WS* "your opponents play cost" ManaValue "more"
EffectExtraRoll     ::= "if you would roll one or more dice, instead roll that many dice plus one and ignore the roll of your choice"
EffectRollAddOne    ::= "if you would roll a die, you may add 1 to its result. (choose after you see the result.)"
EffectResupplyLookAt2 ::= "if you would [resupply], instead look at the top two cards of your deck. put one in reserve, and discard the other"
